###
POST  http://localhost:9000/api/users HTTP/1.1
Content-Type: application/json

{
  "nombres": "Christian",
  "apellidos": "Solano",
  "edad": 24,
  "sexo": "Masculino",
  "fechaNacimiento": "2000-03-31",
  "pais": "Colombia",
  "email": "hosddlassddkkdsdss3@gmail.com",
  "password": "bmth310333"
}



###
GET http://localhost:9000/api/users


###
POST  http://localhost:9000/api/login HTTP/1.1
Content-Type: application/json

{
  "email": "holassss3@gmail.com",
  "password": "bmth310333"
}

